name: Publish package to GitHub Package Registry

on:
  release:
    types:
      - published

jobs:
  Publish:
    name: Publish to GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        with:
          fetch-depth: 0
      - name: Use Node.js v16 with GitHub Package Registry
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          cache: yarn
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Publish
        run: npm publish || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
