name: Publish package to GitHub Package Registry

on:
  release:
    types:
      - published

jobs:
  Publish:
    name: Publish to GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          fetch-depth: 0
      - name: Use Node.js v16 with GitHub Package Registry
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3
        with:
          node-version: 16
          cache: yarn
          registry-url: https://npm.pkg.github.com
      - name: Install Dependencies
        run: yarn --immutable
      - name: Publish
        run: npm publish || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
